
spring:
  profiles:
    active: dev

---
# 开发/测试环境
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/bigdate
    username: root
    password: Jjuyuwang.001

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true